// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SRMMS.Models;

#nullable disable

namespace SRMMS.Migrations
{
    [DbContext(typeof(SRMMSContext))]
    partial class SRMMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SRMMS.Models.Account", b =>
                {
                    b.Property<int>("AccId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("acc_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccId"), 1L, 1);

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("full_name");

                    b.Property<string>("Password")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("phone");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("AccId");

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("SRMMS.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Booking_id");

                    b.Property<int?>("AccId")
                        .HasColumnType("int")
                        .HasColumnName("acc_id");

                    b.Property<int?>("NumberOfPeople")
                        .HasColumnType("int");

                    b.Property<string>("Shift")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TimeBooking")
                        .HasColumnType("datetime")
                        .HasColumnName("Time_booking");

                    b.HasKey("BookingId");

                    b.HasIndex("AccId");

                    b.ToTable("Booking", (string)null);
                });

            modelBuilder.Entity("SRMMS.Models.Category", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cat_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatId"), 1L, 1);

                    b.Property<string>("CatName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cat_name");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("description");

                    b.HasKey("CatId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SRMMS.Models.Combo", b =>
                {
                    b.Property<int>("ComboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("combo_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComboId"), 1L, 1);

                    b.Property<string>("ComboDiscription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("combo_discription");

                    b.Property<string>("ComboImg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("combo_img");

                    b.Property<decimal?>("ComboMoney")
                        .HasColumnType("money")
                        .HasColumnName("combo_money");

                    b.Property<string>("ComboName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("combo_name");

                    b.Property<bool?>("ComboStatus")
                        .HasColumnType("bit")
                        .HasColumnName("combo_status");

                    b.HasKey("ComboId");

                    b.ToTable("Combo", (string)null);
                });

            modelBuilder.Entity("SRMMS.Models.ComboDetail", b =>
                {
                    b.Property<int>("ComboId")
                        .HasColumnType("int")
                        .HasColumnName("combo_id");

                    b.Property<int?>("ProId")
                        .HasColumnType("int")
                        .HasColumnName("pro_id");

                    b.HasIndex("ComboId");

                    b.HasIndex("ProId");

                    b.ToTable("Combo_Detail", (string)null);
                });

            modelBuilder.Entity("SRMMS.Models.DiscountCode", b =>
                {
                    b.Property<int>("CodeId")
                        .HasColumnType("int")
                        .HasColumnName("code_id");

                    b.Property<string>("CodeDetail")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("code_detail");

                    b.Property<double?>("DiscountValue")
                        .HasColumnType("float")
                        .HasColumnName("discount_value");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("CodeId");

                    b.ToTable("Discount_code", (string)null);
                });

            modelBuilder.Entity("SRMMS.Models.Feedback", b =>
                {
                    b.Property<int?>("AccId")
                        .HasColumnType("int")
                        .HasColumnName("acc_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Feedback1")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("feedback");

                    b.Property<int>("FeedbackId")
                        .HasColumnType("int")
                        .HasColumnName("feedback_id");

                    b.Property<int?>("RateStar")
                        .HasColumnType("int")
                        .HasColumnName("rate_star");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasIndex("AccId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("SRMMS.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<int?>("CodeId")
                        .HasColumnType("int")
                        .HasColumnName("code_id");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("date")
                        .HasColumnName("order_date");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<int?>("TableId")
                        .HasColumnType("int")
                        .HasColumnName("table_id");

                    b.Property<decimal?>("TotalMoney")
                        .HasColumnType("money")
                        .HasColumnName("totalMoney");

                    b.HasKey("OrderId");

                    b.HasIndex("CodeId");

                    b.HasIndex("TableId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("SRMMS.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"), 1L, 1);

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money")
                        .HasColumnName("price");

                    b.Property<int?>("ProId")
                        .HasColumnType("int")
                        .HasColumnName("pro_id");

                    b.Property<int?>("Quantiity")
                        .HasColumnType("int")
                        .HasColumnName("quantiity");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProId");

                    b.ToTable("Order_Details", (string)null);
                });

            modelBuilder.Entity("SRMMS.Models.PointList", b =>
                {
                    b.Property<int>("PointId")
                        .HasColumnType("int")
                        .HasColumnName("point_id");

                    b.Property<int?>("AccId")
                        .HasColumnType("int")
                        .HasColumnName("acc_id");

                    b.Property<double?>("NumberPonit")
                        .HasColumnType("float")
                        .HasColumnName("number_ponit");

                    b.HasKey("PointId");

                    b.HasIndex("AccId");

                    b.ToTable("Point_List", (string)null);
                });

            modelBuilder.Entity("SRMMS.Models.Product", b =>
                {
                    b.Property<int>("ProId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pro_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProId"), 1L, 1);

                    b.Property<int?>("CatId")
                        .HasColumnType("int")
                        .HasColumnName("cat_id");

                    b.Property<string>("ProCalories")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("pro_calories");

                    b.Property<string>("ProDiscription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pro_discription");

                    b.Property<string>("ProImg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pro_img");

                    b.Property<string>("ProName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("pro_name");

                    b.Property<decimal?>("ProPrice")
                        .HasColumnType("money")
                        .HasColumnName("pro_price");

                    b.Property<bool?>("ProStatus")
                        .HasColumnType("bit")
                        .HasColumnName("pro_status");

                    b.HasKey("ProId")
                        .HasName("PK_Menu");

                    b.HasIndex("CatId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SRMMS.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("description");

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("SRMMS.Models.StatusTable", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Status_id");

                    b.Property<string>("StatusName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Status_name");

                    b.HasKey("StatusId");

                    b.ToTable("StatusTable", (string)null);
                });

            modelBuilder.Entity("SRMMS.Models.Table", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("table_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"), 1L, 1);

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("Booking_id");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<string>("TableName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("table_name");

                    b.Property<int?>("TableOfPeople")
                        .HasColumnType("int");

                    b.HasKey("TableId");

                    b.ToTable("Table", (string)null);
                });

            modelBuilder.Entity("SRMMS.Models.Account", b =>
                {
                    b.HasOne("SRMMS.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_Accounts_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SRMMS.Models.Booking", b =>
                {
                    b.HasOne("SRMMS.Models.Account", "Acc")
                        .WithMany("Bookings")
                        .HasForeignKey("AccId")
                        .HasConstraintName("FK_Booking_Accounts");

                    b.HasOne("SRMMS.Models.Table", "BookingNavigation")
                        .WithOne("Booking")
                        .HasForeignKey("SRMMS.Models.Booking", "BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_Booking_Table");

                    b.Navigation("Acc");

                    b.Navigation("BookingNavigation");
                });

            modelBuilder.Entity("SRMMS.Models.ComboDetail", b =>
                {
                    b.HasOne("SRMMS.Models.Combo", "Combo")
                        .WithMany()
                        .HasForeignKey("ComboId")
                        .IsRequired()
                        .HasConstraintName("FK_Combo Detail_Combo");

                    b.HasOne("SRMMS.Models.Product", "Pro")
                        .WithMany()
                        .HasForeignKey("ProId")
                        .HasConstraintName("FK_Combo Detail_Menu");

                    b.Navigation("Combo");

                    b.Navigation("Pro");
                });

            modelBuilder.Entity("SRMMS.Models.Feedback", b =>
                {
                    b.HasOne("SRMMS.Models.Account", "Acc")
                        .WithMany()
                        .HasForeignKey("AccId")
                        .HasConstraintName("FK_Feedback_Accounts");

                    b.Navigation("Acc");
                });

            modelBuilder.Entity("SRMMS.Models.Order", b =>
                {
                    b.HasOne("SRMMS.Models.DiscountCode", "Code")
                        .WithMany("Orders")
                        .HasForeignKey("CodeId")
                        .HasConstraintName("FK_Order_Discount_code");

                    b.HasOne("SRMMS.Models.Table", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId")
                        .HasConstraintName("FK_Order_Table");

                    b.Navigation("Code");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("SRMMS.Models.OrderDetail", b =>
                {
                    b.HasOne("SRMMS.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_Order_Details_Order");

                    b.HasOne("SRMMS.Models.Product", "Pro")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProId")
                        .HasConstraintName("FK_Order_Details_Products");

                    b.Navigation("Order");

                    b.Navigation("Pro");
                });

            modelBuilder.Entity("SRMMS.Models.PointList", b =>
                {
                    b.HasOne("SRMMS.Models.Account", "Acc")
                        .WithMany("PointLists")
                        .HasForeignKey("AccId")
                        .HasConstraintName("FK_Point_List_Accounts");

                    b.Navigation("Acc");
                });

            modelBuilder.Entity("SRMMS.Models.Product", b =>
                {
                    b.HasOne("SRMMS.Models.Category", "Cat")
                        .WithMany("Products")
                        .HasForeignKey("CatId")
                        .HasConstraintName("FK_Menu_Categories");

                    b.Navigation("Cat");
                });

            modelBuilder.Entity("SRMMS.Models.StatusTable", b =>
                {
                    b.HasOne("SRMMS.Models.Table", "Status")
                        .WithOne("StatusTable")
                        .HasForeignKey("SRMMS.Models.StatusTable", "StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_StatusTable_Table");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("SRMMS.Models.Account", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("PointLists");
                });

            modelBuilder.Entity("SRMMS.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SRMMS.Models.DiscountCode", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SRMMS.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("SRMMS.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("SRMMS.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("SRMMS.Models.Table", b =>
                {
                    b.Navigation("Booking");

                    b.Navigation("Orders");

                    b.Navigation("StatusTable");
                });
#pragma warning restore 612, 618
        }
    }
}
